### ISSUE TITLE
Tasmota esp32 shows error as **'const char HTTP_HEAD []' redeclared as different kind of symbol** 

### ISSUE THREAD

**Issue by rulshid** [JacekDob/Sonoff-Tasmota#16]
hi, i'm using tasmota in my esp32(with ardino ide 1.8.7), i have downloaded it from https://github.com/JacekDob/Sonoff-Tasmota
and moved(copy) all the files inside the /lib into my ardino/library folder but compiling the program shows this error
and i don't know how to solve the issue please help me ...

**Comment by tomneedham** [comment]
@rulshid How did you resolve this?
