### ISSUE TITLE
compiled .bin images

### ISSUE THREAD

**Issue by Zixim** [JacekDob/Sonoff-Tasmota#3]
Could some one upload compiled .bin images, just like in the Original Tasmota fork ?

**Comment by JacekDob** [comment]
One image released:
https://github.com/JacekDob/Sonoff-Tasmota/releases/tag/v5.12.0

**Comment by Zixim** [comment]
The esp32 I have is brand new out of box, well...plastic baggie 😛 
Never been flashed by me...
Can I flash the firmware with settings as per screenshot ?
Or do I need to worry about bootloader & partitions & other bins ?

![image](https://user-images.githubusercontent.com/7814664/36640458-5d94923a-1a1f-11e8-95f1-3585c5385fb5.png)

**Comment by JacekDob** [comment]
Not sure. Always I've been using Arduino IDE and uploading does everything automatically. But rather bootloader + partitions + boot_app0 + app. I may try to upload them tommorow.

Bootloader and boot_app0 is in Arduino SDK. Partitions and app come from compilation. I would say it is quicker to download Arduino IDE, copy libraries and upload from IDE.

**Comment by JacekDob** [comment]
Added all files in:
https://github.com/JacekDob/Sonoff-Tasmota/releases/tag/v5.12.0
Should work, although not tested.

**Comment by JacekDob** [comment]
Does it work?

**Comment by Zixim** [comment]
I will find out later today, and post back.
Meanwhile I've been experimenting with [ESPEasy32](https://www.letscontrolit.com/wiki/index.php/ESPEasy32) , I think a proper Tasmota for esp32 will be more interesting.

**Comment by Zixim** [comment]
This works : 
![image](https://user-images.githubusercontent.com/7814664/36935506-e9bba464-1ef8-11e8-9c1e-8576218e2bb8.png)

**Comment by JacekDob** [comment]
Should issue be closed?
